version: '3.1'
services:
  odoo:
    user: root 
    image: odoo:14.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    command: sleep infinity 
    volumes:
      #- ./config:/etc/odoo
      - ./extra-addons:/usr/lib/python3/dist-packages/odoo/extra-addons
      - ./config:/usr/lib/python3/dist-packages/odoo
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo